export const GlobalVariables = Object.freeze({
    BASE_API_URL: 'http://127.0.0.1:8000/',
    URLS : {'login':'login/', 'session_user':'session_user/', 'search': 'search/'}, 
    ROLES : {'admin':'Администратор', 'employee':'Сотрудник', 'reader':'Читатель'},
    QSTATUSES : {'new':'Новый', 'progress':'В процессе', 'confirm':'Подтвержден', 'close':'Закрыт', 'archive':'Архивный'},
    MENU : [
        {'title':'Мой профиль', 'uri':'/profile', 'icon':'fa fa-fw fa-user'},
        {'title':'Изменить профиль', 'uri':'/profile/edit', 'icon':'fa fa-fw fa-pencil-square'},
        {'title':'Редактировать адреса', 'uri':'/profile/address', 'icon':'fa fa-fw fa-location-arrow'},
        {'title':'Выйти', 'uri':'/profile/logout', 'icon':'fa fa-fw fa-sign-out'},
        {'title':'Мои запросы', 'uri':'/query', 'icon':'fa fa-fw fa-database'},
    ],
    DELIVERY : {'physical':'Оригинал', 'digital':'Электронная копия', 'copy':'Печатная копия'},
    DSTATUSES : {'new':'Новый', 
                 'confirm':'Подтвержден', 
                 'progress':'Обрабатывается', 
                 'ready':'Готов', 
                 'send':'Опубликован', 
                 'cancel':'Отменен', 
                 'refuse':'Отклонен', 
                 'close':'Закрыт' , 
                 'recieve':'Получен',
                 'mba':'В отделе МБА',
                 'renew':'Требуется продление',
                 'retrieve':'Возвращается фондодержателю'},
});